version: 2
updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "@types/babel*"
          - "babel-plugin-*"
      jest:
        patterns:
          - "@jest/*"
          - "@types/jest"
          - "jest*"
          - "ts-jest*"
      minor-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: Dependabot
